development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # Heroku
  # url: <%= ENV.fetch("REDISCLOUD_URL") %>

  # Digital Ocean
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

  channel_prefix: myPortfolio_production
